[workspace]
members = [
    "apps/fcs_a",
    "apps/fcs_b",
    "apps/plant",
    "crates/wrapper",
    "crates/agent",
]

[workspace.dependencies]
wrapper = { path = "crates/wrapper" }

tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
capnp = "0.14"
