[workspace]
resolver = "2"
members = [
    "apps/fcs_a",
    "apps/fcs_b",
    "apps/plant",
    "crates/wrapper",
    "crates/agent",
]

[workspace.dependencies]
wrapper = { path = "crates/wrapper" }

serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
capnp = "0.14"

[workspace.dependencies.uuid]
version = "1.7.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]