tasks:
  - id: 6acdc42f-fb43-418d-b12f-1b7b0cbafba6
    actions:
      - !AddComponent
        id: 0bab7599-4dad-455f-adec-d30663db087d
        data:
          app-id: 9a069153-c335-47c5-a653-dec6c0e7c280
          component: plant
          version: 1.0.0

      - !AddComponent
        id: 3c52ef52-e201-4aad-a91b-dfce789e4113
        data:
          app-id: 4d2f439b-ae60-42b6-ae45-b4db5d020f21
          component: fcs_a
          version: 1.0.0

      - !AddRoute
        id: 4e682edb-22f1-42bd-995b-6282f114688e
        data:
          source:
            app-id: 9a069153-c335-47c5-a653-dec6c0e7c280
            channel-id: 1
          destination:
            app-id: 4d2f439b-ae60-42b6-ae45-b4db5d020f21
            channel-id: 1

      - !AddRoute
        id: f6879e8a-a42a-49d2-8482-7827408a7775
        data:
          source:
            app-id: 4d2f439b-ae60-42b6-ae45-b4db5d020f21
            channel-id: 2
          destination:
            app-id: 9a069153-c335-47c5-a653-dec6c0e7c280
            channel-id: 2

      - !StartComponent
        id: 2308c934-60f7-42db-8abd-eb005935505c
        data:
          app-id: 9a069153-c335-47c5-a653-dec6c0e7c280

      - !StartComponent
        id: bc4abf66-d2d4-4d6f-bf1f-5260bb9f318b
        data:
          app-id: 4d2f439b-ae60-42b6-ae45-b4db5d020f21
