tasks:
  - id: 8327c2a1-0dbb-425e-aece-897c28c3f9b2
    actions:
      - !AddComponent
        id: f3fd3273-750c-480c-ad84-6c9d700b75d6
        data:
          component-id: a8b72b60-d420-4c9a-8211-3afb36a1af7a
          component: agent
          core: 2
          version: 1.0.0

  - id: 5e1ec06d-6b0d-4897-a1ca-ab04e1f83be7
    actions:
      - !StartComponent
        id: f8b89ead-0d83-4165-9c2b-e80013377580
        data:
          component-id: a8b72b60-d420-4c9a-8211-3afb36a1af7a

      - !AddRoute
        id: 775df2df-2aaf-4a05-a178-312e76d2a158
        data:
          source:
            endpoint: !component-id a8b72b60-d420-4c9a-8211-3afb36a1af7a
            channel-id: 1
          target:
            endpoint: !runner
            channel-id: 1

      - !SetSchedule
        id: 9b407a3f-d340-4704-b2f1-50b5574547f7
        data:
          frequency: 500
          major-frames:
            - minor-frames:
                - component-id: a8b72b60-d420-4c9a-8211-3afb36a1af7a
