[package]
name = "elafry"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
csv = "1.1"

uuid = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true }

[features]
instrument = []